---
stages:
  - initialize

Setup_Clients_Env:
  stage: initialize
  image:
    name: almalinux:8
  script:
    # Install EPEL and required packages
    - dnf install -y epel-release
    - dnf install -y ansible docker-ce-cli python3-pip
    # Verify installations
    - docker version
    - ANSIBLE_CONFIG=./ansible.cfg ansible --version
    - ANSIBLE_CONFIG=./ansible.cfg ansible all -i hosts -c docker -m ping
    - ANSIBLE_CONFIG=./ansible.cfg ansible-playbook -i hosts -c docker site.yml
  tags:
    - docker
